apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployapp
  minReplicas: 10
  maxReplicas: 15
  targetCPUUtilizationPercentage: 50